# Python, päev 1

Täna õpime Pythoni baas asju kasutama

*Hello,World*

In [1]:
print ("Hello, World!") #sring ehk sõne

Hello, World!

## Andmetüübid

In [2]:
PI = 3.14 # float ehj ujukoma arv
aasta = 2026 # int ehk täisarv
sun_rises_from_eat = True # bool ehk tõeväärtus

In [ ]:
years = [2020, 2021, 2022, 2023, 2024] # list ehk järjend, järjestatud ja muudetav kogum elemente - kindel järjekod, indekseerimine algab nullist
person = {
    "name": "Alice",
    "age" : 30,
    "city" : "New York"
 }# dict ehk sõnastik, võtme väärtuse paaride kogum, muutuv ja järjestamata

fruits = ("apple", "banana", "cherry") #set ehk hulk, järjestatud ja muutumatu kogum elemente
tuple_example  = (1,2,3) #tuple ehk ennik, järjestatud ja muutumatu kogum elemente

## Funktsioonid

In [9]:
def greet():
    print("Hello from a function!") # function ehk funktsioon, koodiplokk, mida saab mitu korda kasutada
    print("And some more things going on in here...")
print("not in function!")

not in function!

In [7]:
print("Hello from a function!")
print("And some more things going on in here...")

Hello from a function!
And some more things going on in here...

In [8]:
greet()

Hello from a function!
And some more things going on in here...

In [13]:
number = 42
f"number is {number}"

'number is 42'

In [28]:
def greet2(name: str, time_of_day: str= "day"):
    print(f"Good {time_of_day}, {name}!")

In [32]:
greet2("Toomas")
greet2("Toomas","evening")
greet2(name = "Toomas", time_of_day="evening")

greet2(time_of_day="evening", name = "Toomas")

Good day, Toomas!
Good evening, Toomas!
Good evening, Toomas!
Good evening, Toomas!

In [36]:
def add(a: int, b: int) -> int:
    return a + b

In [37]:
result = add(1,2)
print(result)

3

## if/else

In [43]:
year = -200000
if year < 0:
    print("B.C")
    if year < -10000:
        print("Stone age..")
elif year == 0:
    print("Happy birthday, Jesus!")
elif year == 1978:
    print("Happy Birthday, Mati!")
else:
    print("A.D.")

B.C
Stone age..

In [46]:
def make_sense_of_this_year(year: int):
    if year < 0:
        print("B.C")
        if year < -10000:
            print("Stone age..")
    elif year == 0:
        print("Happy birthday, Jesus!")
    elif year == 1978:
        print("Happy Birthday, Mati!")
    else:
        print("A.D.")

make_sense_of_this_year(-90)
make_sense_of_this_year(year=-90)

B.C
B.C

In [47]:
import datetime

datetime.date.today()

datetime.date(2026, 4, 9)

In [51]:
def print_year(year: int):
    if year < 0:
        print(f"{abs(year)} B.C")
    else:
        print(f"{abs(year)} A.D")

print_year(-90)
print_year(2025)

90 B.C
2025 A.D

In [56]:
def print_year(year: int)-> str:
    return f"{abs(year)}B.C" if year < 0 else f"{abs(year)} A.D"

print_year(-90)
print_year(2025)

'2025 A.D'

In [58]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!

## For loop

In [55]:
years = [2021, 2022, 2023,2024,2025]
for year in years:
    print (f"Happy start of {year}")

Happy start of 2021
Happy start of 2022
Happy start of 2023
Happy start of 2024
Happy start of 2025

## Pandas

In [61]:
import pandas as pd

In [59]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sipsik\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sipsik\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\sipsik\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.3 MB/s eta 0:00:08
   --- ------------------------------------ 0.8/9.9 MB 1.3 MB/s eta 0:00:07
   ----- ---------------------------------- 1.3/9.9 MB 1.4 MB/s eta 0:00:07
   ------ --------------------------------- 1.6/9.9 MB 1.5 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.9 MB 1.4 MB/s eta 0:00:06
   -------- ------------------------------- 2.1/9.9 MB 1.4 MB/s eta 0:00:06
   --------- ------------------------------ 2.4/9.9 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.9 MB 1.5 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.9 MB 1.5 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.6 MB/s eta 0:00:04
   --------------- ------------------------ 3.9/9.9 MB 1.5 MB/s eta 0:00:04
   ----------------- ---------------------- 4.2/9.9 MB 1.5 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.9 MB 1.5 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.9 MB 1.5 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.5 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.9 MB 1.4 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.9 MB 1.4 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.4 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.9 MB 1.4 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.9 MB 1.4 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.4 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.9 MB 1.4 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.4 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.4 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.9 MB 1.4 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.9 MB 1.4 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 1.4 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 1.4 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 1.4 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 1.4 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 1.4 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.4 MB/s  0:00:07
Downloading numpy-2.4.4-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.4 MB 2.0 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.4 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.6/12.4 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.4 MB 2.0 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.4 MB 1.9 MB/s eta 0:00:06
   -------- ------------------------------- 2.6/12.4 MB 2.0 MB/s eta 0:00:06
   ---------- ----------------------------- 3.1/12.4 MB 1.9 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.4 MB 1.9 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.4 MB 2.0 MB/s eta 0:00:05
   -------------- ------------------------- 4.5/12.4 MB 2.0 MB/s eta 0:00:05
   --------------- ------------------------ 4.7/12.4 MB 2.0 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.4 MB 2.0 MB/s eta 0:00:04
   ------------------ --------------------- 5.8/12.4 MB 2.0 MB/s eta 0:00:04
   -------------------- ------------------- 6.3/12.4 MB 2.1 MB/s eta 0:00:03
   --------------------- ------------------ 6.8/12.4 MB 2.1 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.4 MB 2.1 MB/s eta 0:00:03
   ------------------------ --------------- 7.6/12.4 MB 2.1 MB/s eta 0:00:03
   -------------------------- ------------- 8.1/12.4 MB 2.1 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.4 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.4 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.4 MB 2.1 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 2.1 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 2.1 MB/s  0:00:06
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.4.4 pandas-3.0.2

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\Sipsik\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
?pd.DataFrame

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
    If ``data`` is DataFrame then is ignored.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {"col1": [1, 2], "col2": [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {"col1": [0, 1, 2, 3], "col2": pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(
...     np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"]
... )
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array(
...     [(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...     dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")],
... )
>>> df3 = pd.DataFrame(data, columns=["c", "a"])
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           c:\users\sipsik\appdata\local\python\pythoncore-3.14-64\lib\site-packages\pandas\__init__.py
Type:           type
Subclasses:     SubclassedDataFrame

In [63]:
?pd.read.csv

Object `pd.read.csv` not found.

In [67]:
data = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [30,25,35],
    "city": ["York", "Los", "Chi"]
})
data

      name  age  city
0    Alice   30  York
1      Bob   25   Los
2  Charlie   35   Chi

In [69]:
data.to_csv("not_very_sensible_data.csv", index=False)

In [70]:
people = pd.read_csv("not_very_sensible_data.csv")
people

      name  age  city
0    Alice   30  York
1      Bob   25   Los
2  Charlie   35   Chi

In [72]:
people["name"]

0      Alice
1        Bob
2    Charlie
Name: name, dtype: str

In [73]:
people[["name"]]

      name
0    Alice
1      Bob
2  Charlie

In [74]:
people[["name", "age"]]

      name  age
0    Alice   30
1      Bob   25
2  Charlie   35

In [75]:
!pip install duckdb

Collecting duckdb
  Downloading duckdb-1.5.1-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.1-cp314-cp314-win_amd64.whl (13.6 MB)
   ---------------------------------------- 0.0/13.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/13.6 MB ? eta -:--:--
    --------------------------------------- 0.3/13.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/13.6 MB 1.2 MB/s eta 0:00:11
   -- ------------------------------------- 0.8/13.6 MB 1.2 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/13.6 MB 1.2 MB/s eta 0:00:11
   --- ------------------------------------ 1.3/13.6 MB 1.2 MB/s eta 0:00:11
   ---- ----------------------------------- 1.6/13.6 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/13.6 MB 1.2 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/13.6 MB 1.2 MB/s eta 0:00:10
   ------ --------------------------------- 2.4/13.6 MB 1.2 MB/s eta 0:00:10
   ------- -------------------------------- 2.6/13.6 MB 1.2 MB/s eta 0:00:10
   -------- ------------------------------- 2.9/13.6 MB 1.1 MB/s eta 0:00:10
   --------- ------------------------------ 3.1/13.6 MB 1.2 MB/s eta 0:00:10
   --------- ------------------------------ 3.1/13.6 MB 1.2 MB/s eta 0:00:10
   --------- ------------------------------ 3.1/13.6 MB 1.2 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.4/13.6 MB 1.0 MB/s eta 0:00:10
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ---------- ----------------------------- 3.7/13.6 MB 752.1 kB/s eta 0:00:14
   ----------- ---------------------------- 3.9/13.6 MB 555.6 kB/s eta 0:00:18
   ------------ --------------------------- 4.2/13.6 MB 572.5 kB/s eta 0:00:17
   ------------- -------------------------- 4.5/13.6 MB 596.8 kB/s eta 0:00:16
   -------------- ------------------------- 5.0/13.6 MB 643.3 kB/s eta 0:00:14
   --------------- ------------------------ 5.2/13.6 MB 664.7 kB/s eta 0:00:13
   ---------------- ----------------------- 5.5/13.6 MB 683.9 kB/s eta 0:00:12
   ---------------- ----------------------- 5.8/13.6 MB 700.5 kB/s eta 0:00:12
   ----------------- ---------------------- 6.0/13.6 MB 715.2 kB/s eta 0:00:11
   ------------------ --------------------- 6.3/13.6 MB 728.8 kB/s eta 0:00:11
   -------------------- ------------------- 6.8/13.6 MB 761.5 kB/s eta 0:00:09
   --------------------- ------------------ 7.3/13.6 MB 806.5 kB/s eta 0:00:08
   ----------------------- ---------------- 7.9/13.6 MB 846.2 kB/s eta 0:00:07
   ------------------------ --------------- 8.4/13.6 MB 888.8 kB/s eta 0:00:06
   -------------------------- ------------- 8.9/13.6 MB 919.7 kB/s eta 0:00:06
   -------------------------- ------------- 9.2/13.6 MB 934.3 kB/s eta 0:00:05
   ---------------------------- ----------- 9.7/13.6 MB 961.1 kB/s eta 0:00:05
   ------------------------------ --------- 10.2/13.6 MB 990.0 kB/s eta 0:00:04
   ------------------------------ --------- 10.5/13.6 MB 1.0 MB/s eta 0:00:04
   ------------------------------- -------- 10.7/13.6 MB 1.0 MB/s eta 0:00:03
   --------------------------------- ------ 11.3/13.6 MB 1.0 MB/s eta 0:00:03
   ---------------------------------- ----- 11.8/13.6 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 12.1/13.6 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 12.6/13.6 MB 1.1 MB/s eta 0:00:01
   ------------------------------------- -- 12.8/13.6 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  13.4/13.6 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 13.6/13.6 MB 1.1 MB/s  0:00:12
Installing collected packages: duckdb
Successfully installed duckdb-1.5.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [76]:
import duckdb

In [77]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\sipsik\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 2.1 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.1 MB 2.2 MB/s eta 0:00:04
   --------- ------------------------------ 1.8/8.1 MB 2.2 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.1 MB 2.2 MB/s eta 0:00:03
   ------------ --------------------------- 2.6/8.1 MB 2.2 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.1 MB 2.2 MB/s eta 0:00:03
   ---------------- ----------------------- 3.4/8.1 MB 2.2 MB/s eta 0:00:03
   ------------------- -------------------- 3.9/8.1 MB 2.2 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.1 MB 2.1 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.1 MB 2.1 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.1 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 5.8/8.1 MB 2.1 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.1 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 2.1 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 2.1 MB/s  0:00:03
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 991.7 kB/s eta 0:00:38
    --------------------------------------- 0.5/37.3 MB 991.7 kB/s eta 0:00:38
    --------------------------------------- 0.5/37.3 MB 991.7 kB/s eta 0:00:38
    --------------------------------------- 0.5/37.3 MB 991.7 kB/s eta 0:00:38
    --------------------------------------- 0.5/37.3 MB 991.7 kB/s eta 0:00:38
    --------------------------------------- 0.5/37.3 MB 991.7 kB/s eta 0:00:38
    --------------------------------------- 0.8/37.3 MB 379.5 kB/s eta 0:01:37
    --------------------------------------- 0.8/37.3 MB 379.5 kB/s eta 0:01:37
   - -------------------------------------- 1.0/37.3 MB 417.0 kB/s eta 0:01:27
   - -------------------------------------- 1.0/37.3 MB 417.0 kB/s eta 0:01:27
   - -------------------------------------- 1.0/37.3 MB 417.0 kB/s eta 0:01:27
   - -------------------------------------- 1.3/37.3 MB 429.3 kB/s eta 0:01:24
   - -------------------------------------- 1.6/37.3 MB 497.6 kB/s eta 0:01:12
   - -------------------------------------- 1.6/37.3 MB 497.6 kB/s eta 0:01:12
   - -------------------------------------- 1.8/37.3 MB 499.9 kB/s eta 0:01:11
   - -------------------------------------- 1.8/37.3 MB 499.9 kB/s eta 0:01:11
   -- ------------------------------------- 2.1/37.3 MB 521.5 kB/s eta 0:01:08
   -- ------------------------------------- 2.1/37.3 MB 521.5 kB/s eta 0:01:08
   -- ------------------------------------- 2.1/37.3 MB 521.5 kB/s eta 0:01:08
   -- ------------------------------------- 2.4/37.3 MB 508.0 kB/s eta 0:01:09
   -- ------------------------------------- 2.4/37.3 MB 508.0 kB/s eta 0:01:09
   -- ------------------------------------- 2.4/37.3 MB 508.0 kB/s eta 0:01:09
   -- ------------------------------------- 2.4/37.3 MB 508.0 kB/s eta 0:01:09
   -- ------------------------------------- 2.6/37.3 MB 476.9 kB/s eta 0:01:13
   -- ------------------------------------- 2.6/37.3 MB 476.9 kB/s eta 0:01:13
   -- ------------------------------------- 2.6/37.3 MB 476.9 kB/s eta 0:01:13
   --- ------------------------------------ 2.9/37.3 MB 458.0 kB/s eta 0:01:16
   --- ------------------------------------ 2.9/37.3 MB 458.0 kB/s eta 0:01:16
   --- ------------------------------------ 3.1/37.3 MB 471.8 kB/s eta 0:01:13
   --- ------------------------------------ 3.1/37.3 MB 471.8 kB/s eta 0:01:13
   --- ------------------------------------ 3.4/37.3 MB 491.8 kB/s eta 0:01:09
   --- ------------------------------------ 3.4/37.3 MB 491.8 kB/s eta 0:01:09
   --- ------------------------------------ 3.7/37.3 MB 498.3 kB/s eta 0:01:08
   ---- ----------------------------------- 3.9/37.3 MB 508.5 kB/s eta 0:01:06
   ---- ----------------------------------- 4.2/37.3 MB 532.0 kB/s eta 0:01:03
   ---- ----------------------------------- 4.2/37.3 MB 532.0 kB/s eta 0:01:03
   ---- ----------------------------------- 4.5/37.3 MB 546.4 kB/s eta 0:01:01
   ----- ---------------------------------- 4.7/37.3 MB 565.1 kB/s eta 0:00:58
   ----- ---------------------------------- 5.0/37.3 MB 581.0 kB/s eta 0:00:56
   ----- ---------------------------------- 5.2/37.3 MB 594.7 kB/s eta 0:00:54
   ----- ---------------------------------- 5.5/37.3 MB 602.0 kB/s eta 0:00:53
   ----- ---------------------------------- 5.5/37.3 MB 602.0 kB/s eta 0:00:53
   ------ --------------------------------- 5.8/37.3 MB 611.8 kB/s eta 0:00:52
   ------ --------------------------------- 6.0/37.3 MB 617.4 kB/s eta 0:00:51
   ------ --------------------------------- 6.0/37.3 MB 617.4 kB/s eta 0:00:51
   ------ --------------------------------- 6.3/37.3 MB 627.4 kB/s eta 0:00:50
   ------- -------------------------------- 6.6/37.3 MB 637.6 kB/s eta 0:00:49
   ------- -------------------------------- 6.8/37.3 MB 647.2 kB/s eta 0:00:48
   ------- -------------------------------- 6.8/37.3 MB 647.2 kB/s eta 0:00:48
   ------- -------------------------------- 6.8/37.3 MB 647.2 kB/s eta 0:00:48
   ------- -------------------------------- 6.8/37.3 MB 647.2 kB/s eta 0:00:48
   ------- -------------------------------- 7.1/37.3 MB 625.6 kB/s eta 0:00:49
   ------- -------------------------------- 7.1/37.3 MB 625.6 kB/s eta 0:00:49
   ------- -------------------------------- 7.1/37.3 MB 625.6 kB/s eta 0:00:49
   ------- -------------------------------- 7.1/37.3 MB 625.6 kB/s eta 0:00:49
   ------- -------------------------------- 7.1/37.3 MB 625.6 kB/s eta 0:00:49
   ------- -------------------------------- 7.3/37.3 MB 596.5 kB/s eta 0:00:51
   ------- -------------------------------- 7.3/37.3 MB 596.5 kB/s eta 0:00:51
   ------- -------------------------------- 7.3/37.3 MB 596.5 kB/s eta 0:00:51
   -------- ------------------------------- 7.6/37.3 MB 580.4 kB/s eta 0:00:52
   -------- ------------------------------- 7.6/37.3 MB 580.4 kB/s eta 0:00:52
   -------- ------------------------------- 7.6/37.3 MB 580.4 kB/s eta 0:00:52
   -------- ------------------------------- 7.6/37.3 MB 580.4 kB/s eta 0:00:52
   -------- ------------------------------- 7.6/37.3 MB 580.4 kB/s eta 0:00:52
   -------- ------------------------------- 7.9/37.3 MB 560.7 kB/s eta 0:00:53
   -------- ------------------------------- 8.4/37.3 MB 584.0 kB/s eta 0:00:50
   --------- ------------------------------ 9.2/37.3 MB 631.9 kB/s eta 0:00:45
   ---------- ----------------------------- 10.0/37.3 MB 677.9 kB/s eta 0:00:41
   ----------- ---------------------------- 10.7/37.3 MB 722.8 kB/s eta 0:00:37
   ------------ --------------------------- 11.8/37.3 MB 781.5 kB/s eta 0:00:33
   ------------- -------------------------- 12.6/37.3 MB 824.4 kB/s eta 0:00:30
   -------------- ------------------------- 13.4/37.3 MB 866.4 kB/s eta 0:00:28
   --------------- ------------------------ 14.4/37.3 MB 919.9 kB/s eta 0:00:25
   ---------------- ----------------------- 15.2/37.3 MB 959.2 kB/s eta 0:00:24
   ----------------- ---------------------- 16.0/37.3 MB 997.9 kB/s eta 0:00:22
   ------------------ --------------------- 17.0/37.3 MB 1.0 MB/s eta 0:00:20
   ------------------- -------------------- 17.8/37.3 MB 1.1 MB/s eta 0:00:18
   ------------------- -------------------- 18.6/37.3 MB 1.1 MB/s eta 0:00:17
   --------------------- ------------------ 19.7/37.3 MB 1.2 MB/s eta 0:00:16
   --------------------- ------------------ 20.4/37.3 MB 1.2 MB/s eta 0:00:15
   ---------------------- ----------------- 21.2/37.3 MB 1.2 MB/s eta 0:00:14
   ----------------------- ---------------- 22.0/37.3 MB 1.3 MB/s eta 0:00:13
   ------------------------ --------------- 22.8/37.3 MB 1.3 MB/s eta 0:00:12
   ------------------------- -------------- 23.9/37.3 MB 1.3 MB/s eta 0:00:11
   -------------------------- ------------- 24.6/37.3 MB 1.4 MB/s eta 0:00:10
   --------------------------- ------------ 25.4/37.3 MB 1.4 MB/s eta 0:00:09
   ---------------------------- ----------- 26.2/37.3 MB 1.4 MB/s eta 0:00:08
   ---------------------------- ----------- 27.0/37.3 MB 1.4 MB/s eta 0:00:08
   ------------------------------ --------- 28.0/37.3 MB 1.5 MB/s eta 0:00:07
   ------------------------------ --------- 28.8/37.3 MB 1.5 MB/s eta 0:00:06
   ------------------------------- -------- 29.6/37.3 MB 1.5 MB/s eta 0:00:05
   -------------------------------- ------- 30.7/37.3 MB 1.6 MB/s eta 0:00:05
   --------------------------------- ------ 31.5/37.3 MB 1.6 MB/s eta 0:00:04
   ---------------------------------- ----- 32.2/37.3 MB 1.6 MB/s eta 0:00:04
   ----------------------------------- ---- 33.0/37.3 MB 1.6 MB/s eta 0:00:03
   ------------------------------------ --- 33.8/37.3 MB 1.7 MB/s eta 0:00:03
   ------------------------------------- -- 34.6/37.3 MB 1.7 MB/s eta 0:00:02
   -------------------------------------- - 35.7/37.3 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 1.8 MB/s  0:00:21
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [78]:
from sklearn.datasets import load_iris

In [159]:
from sklearn.datasets import load_iris
import pandas as pd

iris_data = load_iris()
iris = pd.DataFrame(iris_data.data, columns = iris_data.feature_names)
iris['target'] = iris_data.target
iris['species'] = iris['target'].map(dict(enumerate(iris_data.target_names)))
iris.pop('target')
iris = iris.rename(columns={
    "sepal length (cm)" : "sepal_length",
    "sepal width (cm)" : "sepal width",
    "petal length (cm)" : "petal_length",
    "petal width (cm)" : "petal width"
})
iris

     sepal_length  sepal width  petal_length  petal width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [160]:
iris.to_csv("iris.csv", index=False)

In [84]:
duckdb.sql("select 'Hello, world!' AS greeting")

┌───────────────┐
│   greeting    │
│    varchar    │
├───────────────┤
│ Hello, world! │
└───────────────┘

In [85]:
duckdb.sql("select 'Hello, world!' ")

┌─────────────────┐
│ 'Hello, world!' │
│     varchar     │
├─────────────────┤
│ Hello, world!   │
└─────────────────┘

In [88]:
duckdb.sql("""
    SELECT* 
    FROM iris
    limit 5
""").df

<bound method pybind11_detail_function_record_v1_msvc_mt_mscver1944.df of ┌───────────────────┬──────────────────┬───────────────────┬──────────────────┬─────────┐
│ sepal length (cm) │ sepal width (cm) │ petal length (cm) │ petal width (cm) │ species │
│      double       │      double      │      double       │      double      │ varchar │
├───────────────────┼──────────────────┼───────────────────┼──────────────────┼─────────┤
│               5.1 │              3.5 │               1.4 │              0.2 │ setosa  │
│               4.9 │              3.0 │               1.4 │              0.2 │ setosa  │
│               4.7 │              3.2 │               1.3 │              0.2 │ setosa  │
│               4.6 │              3.1 │               1.5 │              0.2 │ setosa  │
│               5.0 │              3.6 │               1.4 │              0.2 │ setosa  │
└───────────────────┴──────────────────┴───────────────────┴──────────────────┴─────────┘
>

In [97]:
duckdb.sql("""
    SELECT
       species,
       AVG (petal_length) as avg_petal_legth
    FROM iris
       GROUP BY species,
       ORDER BY avg_petal_legth desc
""").df()

      species  avg_petal_legth
0   virginica            5.552
1  versicolor            4.260
2      setosa            1.462

HARJUTUSED

In [102]:
def funktsioon_enne_voi_parast_kristust(aasta: int) -> str:
    if aasta < 0 : 
        return f"{abs(aasta)} B.C."
    else:
        return f"{aasta} A.D."
funktsioon_enne_voi_parast_kristust(12)

'12 A.D.'

In [127]:
inimesed = ['Kati', 'Mati', 'Silver', 'Hannes']
numbrid = ['esimene', 'teine', 'kolmas', 'neljas']

jarjekorranumber = 0

for nimi in inimesed:
    jarjekord = numbrid[jarjekorranumber].capitalize()
    if len(nimi) > 4:
         print(f"{jarjekord} inimene kannab pikka nime {nimi.upper()}.")
    else:
         print(f"{jarjekord} inimene kannab lühikest nime {nimi.upper()}.")
    jarjekorranumber += 1

Esimene inimene kannab lühikest nime KATI.
Teine inimene kannab lühikest nime MATI.
Kolmas inimene kannab pikka nime SILVER.
Neljas inimene kannab pikka nime HANNES.

## HARJUTUS DAY 2

- vaja leida kogu hind
- kui hind on üle 100, siis 20% alla
- kui hind on üle 50, siis 10% alla
- lõpptulemuseks on funktsioon get.price(hinnad)

In [158]:
# minu lahendus
hinnad = [120,45,89,200,33,75,150,10,99,101]

def get_price(list_sisendiks: int) ->float:
    uued_hinnad = []
    for hind in list_sisendiks:
        if hind > 100:
            uus_hind = hind*0.8
            uued_hinnad.append(uus_hind)
            
        elif hind > 50:
            uus_hind = hind*0.9
            uued_hinnad.append(uus_hind)

        else:
            uued_hinnad.append(hind)

    return sum(uued_hinnad)
lopphind = get_price(hinnad)

print(f"Kogu hind on: {lopphind}€ ")

Kogu hind on: 781.5€

In [156]:
# õpetaja lahendus
hinnad = [120,45,89,200,33,75,150,10,99,101]

def get_discount(price: int) -> float:
        if price > 100:
            return price*0.8
            
        if price > 50:
            return price*0.9
        return price

def get_price(uued_hinnad: list[int]) -> float:
     tulemus = 0
     for uus_hind in uued_hinnad:
          allahindlusega_hind = get_discount(uus_hind)
          tulemus = tulemus + allahindlusega_hind
     return tulemus
     
    
get_price(hinnad)

781.5

In [ ]:
# õpetaja lahendus 2
hinnad = [120,45,89,200,33,75,150,10,99,101]

def get_discount(price: int) -> float:
        if price > 100:
            return price*0.8
            
        if price > 50:
            return price*0.9
        return price

def get_price_short(uued_hinnad: list[int]) -> float:
     return sum([get_discount(hind) for hind in uued_hinnad])

    
get_price_short(hinnad)

781.5